services:
  mongodb-product-service:
    image: mongo:latest
    container_name: mongodb-product-service
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: product-db
    volumes:
      - ./docker/mongodb-product-service-init.js:/docker-entrypoint-initdb.d/init.js:ro
      - mongo-product-data:/data/db

  mysql-order-service:
    image: mysql:latest
    container_name: mysql-order-service
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: order-service
    volumes:
      - mysql-order-data:/var/lib/mysql

volumes:
  mongo-product-data:
  mysql-order-data: