spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order-db
    username: root		
    password: mysql
  jpa:
    hibernate:
        ddl-auto: none
    show-sql: true

server:
  port: 8081

inventoryservice:
  url: http://localhost:8082 
