spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: product-db
      username: root
      password: mongo
      authentication-database: admin
      auto-index-creation: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

server:
  port: 8080