spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: product-service
      username: root
      password: mongo
      authentication-database: admin

server:
  port: 8080