spring:
  datasource:
    url: jdbc:mysql://localhost:3307/inventory-db
    username: root		
    password: mysql
  jpa:
    hibernate:
        ddl-auto: none
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true

server:
  port: 8082

productservice:
  url: http://localhost:8080
